config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'channels#index'
  resources :channels, only: [:index, :show]
end

app/models/channel.rb
class Channel < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/channels_controller.rb
class Admin::ChannelsController < ApplicationController
  def index
    @channels= Channel.all
  end

  def show
    @channel = Channel.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  require 'npr'

  def index
    @channels= Channel.all
  end

  def show
    @channel = Channel.find(params[:id])
    @hash = NPR.get_latest(@channel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/channels/index.html.erb
<h2>Channels#index</h2>

<div class="row">

  <div class="col-xs-12 col-sm-12 col-md-12">
    
    <div class="index-box">
    
      <ul>
	    <% @channels.each do |channel| -%>
		  <li><%= link_to channel.name, channel_path(channel) %></li>
	    <%- end %>
      </ ul>
    
    </div><!-- end index-box -->

  </div><!-- end cols -->

</div><!-- end row -->

app/views/channels/show.html.erb
<h2><%= @channel.name %></h2>

<div class="row">
<%- index = 0 -%>
<% @hash['list']['story'].each do |story| -%>
  <% next unless story['song'] %>
  <%- index += 1 -%>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="music-box">
      <h3><%= story['song'][0]['album']['albumArtist']['$text'] %></h3>
      <% if story['image'][0]['src'] %>
        <p><%= image_tag story['image'][0]['src'].sub(' ', '%20'), width: '250' %></p>
      <% elsif story['thumbnail']['large']['$text'] %>
        <p><%= image_tag "#{story['thumbnail']['large']['$text']}", width: '250'%></p>
      <% elsif story['song'][0]['album']['coverUrl']['$text'] and story['song'][0]['album']['coverUrl']['$text'] != 'N/A'%>
        <p><%= image_tag "http://www.npr.org/#{story['song'][0]['album']['coverUrl']['$text']}", width: '250'%></p>
      <% end %>
      <ul>
        <% story['audio'].each do |audio| %>
          <% next unless audio['title'] and audio['format']['mp3'] %>
          <% audio['format']['mp3'].each do |format| %>
            <% next unless format['type'] == 'mp3' %>
            <li>
              <div class="song-title"><%= link_to audio['title']['$text'], format['$text'] %></div>
              <div class="audio-player"><%= audio_tag format['$text'], autoplay: false, controls: true, title: audio['title']['$text'], rel:"noreferrer" %></div>
            </li>
          <% end %>
        <% end %>
      </ul>
      <br />
      <%= link_to 'View on NPR', story['link'][0]['$text'], class:'btn btn-default btn-lg btn-block', role:'button', target:'_blank' %>
    </div><!-- end .music-box -->
  </div>
  <%- if index.modulo(2).zero? %>
    <div class="clearfix visible-sm-block"></div>
  <% end %>
  <%- if index.modulo(3).zero? %>
    <div class="clearfix visible-md-block visible-lg-block"></div>
  <%- end %>
<%- end %>
</div><!-- end row -->

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NPR-O-MATIC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<%= yield :body || "<body>" %>

  <header>

    <div class="container">
      <h1><a href="/">NPR-O-MATIC</a></h1>
      
      <nav>
        <ul>
          <li><a href="/">home</a></li>
	      <% Channel.all.each do |channel| %>
		    <li><%= link_to channel.name, channel_path(channel) %></li>
	      <%- end %>
        </ul>
      </nav>
      
    </div>
  </header>

  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
  </div>

  <footer>
    <div class="container">
	  <div class="row">
	  
        <div class="col-xs-12 col-sm-4 col-md-4">
          <p>NPR-O-MATIC is created, written by, and maintained by Sarvin Coachbuilder and a team of swell people. It was built as a side project to learn cool, new stuff. Check us out on <a href="#" target="_blank">GitHub</a>.</p>
        </div>
        
        <div class="col-xs-12 col-sm-8 col-md-8">
          <ul class="footer-nav">
            <li><a href="/">home</a></li>
	        <% Channel.all.each do |channel| %>
		      <li><%= link_to channel.name, channel_path(channel) %></li>
	        <%- end %>
	        <%- if user_signed_in? %>
	        	<li><%= link_to("Log Out", destroy_user_session_path, :method => :delete) %></li>
	        <%- end %>
          </ul>
		  <div class="footer-byline">NPR-O-MATIC &copy; 2016 The people that worked on this project. All Rights Reserved.</div>
	    </div>
	    
      </div>
    </div>
  </footer>

</body>
</html>